<script lang="ts">
	let { isOpen, onAccept }: { isOpen: boolean; onAccept: () => void } = $props();
</script>

{#if isOpen}
	<dialog class="modal modal-open">
		<div class="modal-box max-w-2xl">
			<h3 class="font-bold text-lg mb-4">Important Disclaimer</h3>

			<div class="space-y-4 text-sm">
				<p class="font-semibold text-warning">
					⚠️ NOT FINANCIAL ADVICE
				</p>

				<p>
					This website is for <strong>informational and educational purposes only</strong>.
					The content provided is generated by Large Language Models (LLMs) and should NOT be
					used as the basis for any financial, investment, or trading decisions. Furthermore, this website is still actively under development.
				</p>

				<div class="bg-base-200 p-3 rounded-lg">
					<p class="font-semibold mb-2">Key Limitations:</p>
					<ul class="list-disc list-inside space-y-1 ml-2">
						<li>LLMs can and will <strong>hallucinate</strong> (generate false or misleading information)</li>
						<li>Analysis may be incomplete, inaccurate, or outdated</li>
						<li>No warranty or guarantee of accuracy is provided</li>
						<li>Past performance does not indicate future results</li>
					</ul>
				</div>

				<p>
					<strong>Always consult with a qualified financial advisor</strong> before making any
					investment decisions. You are solely responsible for your own financial decisions and
					any consequences thereof.
				</p>

				<div class="border-t border-base-300 pt-4 mt-4">
					<p class="text-error font-bold text-center text-base">
						Making investment decisions based solely on this AI-generated content is an exceptionally bad idea and will almost certainly result in your financial loss.
					</p>
				</div>

				<p class="text-xs opacity-70">
					By continuing to use this website, you acknowledge that you have read and understood
					this disclaimer and agree to use the information provided at your own risk.
				</p>
			</div>

			<div class="modal-action">
				<button class="btn btn-primary" onclick={onAccept}>
					I Understand, and Accept
				</button>
			</div>
		</div>
	</dialog>
{/if}
